### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by andre-esser** [bigclick/gambio-gx-multislider#1]
HAllo,
beim anlegen vom Slider, kommt beim Bild hochladen ein SyntaxError.
Er lädt als kein Bild hoch. Verzeichnisrechte sind gesetzt!

**Comment by xpbemo** [comment]
Hallo, mir gefällt euer Slider sehr gut. Nur was genau bedeutet rekursive schreibrechte? Habe bei Google nicht so recht was dazu gefunden. Ich stelle die Rechte mit FileZilla ein. Besten Dank im Voraus.

**Comment by bigclick** [comment]
Hallo,

rekursiv bedeutet „Dieser Ordner und alle darin enthaltenen“. Das kann man per Hand machen oder aber die Option, die viele Programme bieten, „Recursive“.

**Comment by xpbemo** [comment]
Erstmal vielen Dank für die schnelle Antwort. Sorry, ich steh da ein bisschen auf dem Schlauch. Ich wähle also in FileZilla den Ordner /uploads/ aus, setzte die Rechte auf 666 und klicke an auf alle Unterordner anwenden. Richtig? Oder mus ich anklicken auf alle Unterordner und Dateien anwenden?

**Comment by bigclick** [comment]
Ja, alles korrekt. Ggf. musst du evt. 777 setzen. Probiere aber vorher die 666 aus, das sollte eigentlich reichen.

**Comment by xpbemo** [comment]
Vielen lieben Dank! Es ist wirklich schön, wenn man so schell Hilfe bekommt.
