### ISSUE TITLE
Bilder werden beim Upload in der Größe verändert

### ISSUE THREAD

**Issue by Marktwert** [bigclick/gambio-gx-multislider#10]
Hallo,
1)beim Upload in den Multislider werden die Orginalgrößen der Bilder skaliert und ich kann diese im Multislider nicht mehr verändern. Gibt es hierzu irgendeine Lösung?
2) Wie kann man mehrere Bilder in einer Reihenfolge anzeigen, so dass ein fließender Effekt von Links nach rechts entsteht. 
3)gibt es eine Anleitung für die Bedienung des Multisliders?

**Comment by dsiekiera** [comment]
Wenn ein wenig Zeit ist, werden wir mal ein paar Zeilen zusammenschreiben, aber derzeit schafffen wir es einfach zeitlich nicht.
