### ISSUE TITLE
Multislider Probleme mit GX 2.3.1.3

### ISSUE THREAD

**Issue by andre-esser** [bigclick/gambio-gx-multislider#11]
Hallo,

das MOdul läuft leider nicht unter der o.g. Version.
Gibt es schon ein Fix?

**Comment by Marktwert** [comment]
Hast du das Problem nur beim anlegen eines neuen Sliders? Bei mir läuft er, kann nur keinen neuen mehr anlegen

**Comment by andre-esser** [comment]
Ja genau. Ich kann keinen neuen mehr anlegen.

**Comment by Marktwert** [comment]
Scheinen irgendwie Zugriffe auf die DB nicht zu funktionieren. Wenn Du eine Lösung hast, würdest Du die bitte hier posten? Falls ich es herausfinde mache ich es auch

**Comment by siekiera-media** [comment]
Ich habe derzeit keine gültige Gambio Version. Die muss ich mir erstmal besorgen.

**Comment by andre-esser** [comment]
die kann ich dir senden. was brauchst du denn? sp oder full?

**Comment by Marktwert** [comment]
super, dass uns geholfen wird!!!
