### ISSUE TITLE
Multislider does not work anymore with Gambio version 2.3.1.3

### ISSUE THREAD

**Issue by Marktwert** [bigclick/gambio-gx-multislider#12]
Due to the new version of Gambio it is not possible to save a new slider or a new layer. Further more it is not possible to upload a new picture. The save-button or the upload button seems to be inactive and they do not work any more. Please help. Till the day before yesterday everything was ok but since the update it is wrong. Do you have any ideas?

**Comment by Marktwert** [comment]
just an additional comment: The button new slider works but no other button works

**Comment by siekiera-media** [comment]
Ich denke mal das liegt an einem Javascript Konflikt. Ich versuche das diese Woche noch zu beheben.

**Comment by siekiera-media** [comment]
Ist gefixt. Bitte herunterladen und updaten.
