### ISSUE TITLE
Schade, dass man bzgl. des Sliders keine Antworten bekommt...

### ISSUE THREAD

**Issue by Marktwert** [bigclick/gambio-gx-multislider#13]
...dann muss ich mich wohl mit einem anderen Slider beschäftigen. Es wäre ja schon hilfreich, wenn man sagt, wir machen hier nichts mehr oder es dauert x Wochen. Echt schade, denn der slider war echt gut.

**Comment by bigclick** [comment]
Derzeit sind wir leicht ausgelastet. Aber ich versuche das diese Woche noch zu fixen. Muss mir nur erstmal eine gültige Gambio Version besorgen.

**Comment by Marktwert** [comment]
Super, danke!!!

**Comment by andre-esser** [comment]
@biglick
ich habe die die aktuelle Version zukommen lassen!
