### ISSUE TITLE
Gambio 2.3.1.4

### ISSUE THREAD

**Issue by Th4n4tos** [bigclick/gambio-gx-multislider#14]
Hallo,

der Multislider funktioniert in Gambio V 2.3.xx leider nicht mehr, keine Reaktion im Backend für z.B. Bilderupload usw.
Gibt es evtl. ein Update, oder einen Tip was zu ändern ist?

Gruß

**Comment by siekiera-media** [comment]
Ist gefixt. Bitte herunterladen und updaten.

**Comment by Th4n4tos** [comment]
Hallo,

ich kann die Version leider erst nächste Woche testen, da ich i.M. ein paar Tage frei habe.

Grüße und vielen Dank!

**Comment by Th4n4tos** [comment]
Vielen Dank für das Update

Gruß
