### ISSUE TITLE
Multislider Gambio

### ISSUE THREAD

**Issue by nostromo33** [bigclick/gambio-gx-multislider#15]
Gambio v2.3.1.4

kein Bild einfügen mehr möglich?!

Danke im Voraus

**Comment by siekiera-media** [comment]
Wir sind dran.

**Comment by siekiera-media** [comment]
Ist gefixt. Bitte herunterladen und updaten.

**Comment by nostromo33** [comment]
Tja, beim Besten Willen da geht nix.
Dateien hochgeladen, Rechte überprüft, Cache geleert.
Und es unzt nicht :-)! Kann es sein das noch ein Schritt notwendig ist, habe auch die multislider.sql nochmals importiert im PHPMyAdmin, bringt auch nix.

**Comment by bigclick** [comment]
Du hast auch mal alle Caches gelöscht?

Ich habe das Modul auch von einem anderen User testen lassen, und der meint es läuft tadellos.

Die SQL darf nicht 2x ausgeführt werden, das könnte derbe Probleme in der Datenbank machen.

Wenn Du den Multislider im Admin offen hast, drücke bitte mal STRG+R, für den Mac CMD+R, um alle Scripte aus dem Browsercache zu löschen und neu vom Server zu laden.

**Comment by Marktwert** [comment]
Hallo, 
Bei mir geht es auch nicht, hatte ihn auch in der alten Gambino-Versionsnummer schon in Betrieb

Von meinem iPhone gesendet

Am 30.06.2015 um 19:22 schrieb bigclick <notifications@github.com>:

Du hast auch mal alle Caches gelöscht?

Ich habe das Modul auch von einem anderen User testen lassen, und der meint es läuft tadellos.

Die SQL darf nicht 2x ausgeführt werden, das könnte derbe Probleme in der Datenbank machen.

Wenn Du den Multislider im Admin offen hast, drücke bitte mal STRG+R, für den Mac CMD+R, um alle Scripte aus dem Browsercache zu löschen und neu vom Server zu laden.

**Comment by nostromo33** [comment]
Hallo, also das sql Statment 2x ausführen bringt nur eine Fehlermeldung weil er ein Alter Table nicht ausführen kann, ist ja schon da der Eintrag.
Ja die Caches sind händisch geleert, sowohl der cache Ordner als auch templates_c.
Danach Browser Cache geleert, kein Erfolg.
Das Bild hinzufügen funktioniert nach wie vor nicht.
Gibt es denn ne Möglichkeit den Slider per Script zu löschen, oder muß ich das selbst schreiben?
Dann würde ich mal eine Neuinstallation testen.

**Comment by nostromo33** [comment]
Ach so, was ich noch fragen wollte, wozu ist die gitignore datei da?

**Comment by siekiera-media** [comment]
So, Freunde der Sonne.

Hab das Teil jetzt nochmal überarbeitet und ein paar neue Features hinzugefügt. Hoffe er läuft jetzt.

**Comment by nostromo33** [comment]
Hey, große sache es funzt wieder!!!!!!!
Danke dir!!!!
