### ISSUE TITLE
Multislider wird im Backend nicht angezeigt

### ISSUE THREAD

**Issue by Dopex20** [bigclick/gambio-gx-multislider#17]
Hallo Support,

ich habe die Gambio-Version v2.3.1.1.

Ich habe den Gambio-Multislider exakt nach Anweisung installiert aber im Administrations-Bereich taucht der Menüpunkt "Multislider" nicht auf.

Bitte um Hilfe.

Vielen Dank im Voraus

MfG

M. Rinninger

**Comment by dsiekiera** [comment]
Bitte noch einmal herunterladen und gemäß der README updaten. Dann sollte alles laufen.
