### ISSUE TITLE
Menüpunkt MULTISLIDER im Admin plötzlich verschwunden.

### ISSUE THREAD

**Issue by styrol** [bigclick/gambio-gx-multislider#18]
Ich habe den Multislider im Gambio 2.3.2.0 nach Vorgaben installiert. Von mir wurde ein Slider erstellt - alles kinderleicht und sehr gut zu bearbeiten.
Der Slider im Shop läuft nach wie vor einwandfrei, jedoch ist der Menüpunkt im Adminbereich von einer Sekunde auf die andere verschwunden, ohne dass vom Shop aus eine Änderung oder ein Update gemacht wurde. Ich habe die Dateistruktur nochmals vom Update auf den Server gespielt, die Datenbank durchsucht - ich finde leider den Fehler nicht. 
Meine Seite http://shoppingworld4animals.com/

**Comment by siekiera-media** [comment]
Hallo styrol.

Folgendes kannst du mal testen:
Kannst du, nachdem Du Dich im Admin eingeloggt hast, diese URL aufrufen =>  http://shoppingworld4animals.com/admin/multislider.php?

Wenn nicht, fehlt das Datenbankfeld "multislider" in der Datenbank. Das müsste in der 'admin_access' liegen.

Ist das vorhanden, kann nur noch die Datei 'user_classes/conf/admin_menu/menu_multislider.xml' fehlen. Darin liegt der Link.

**Comment by styrol** [comment]
vielen Dank - beim Überstellen von der Subdomain auf die Hauptdomain muss der Fehler mit der Datenbank passiert sein. Hier war wirklich in der admin_access die Spalte "multislider" nicht mehr vorhanden. Vielen Dank für die rasche Antwort mit den absolut passenden Anweisungen :)
Ich kann den Multislider für den Gambio nur empfehlen

**Comment by dsiekiera** [comment]
Problem gelöst. Thread wird geschlossen.
