### ISSUE TITLE
Gambio 2.5.x.x

### ISSUE THREAD

**Issue by andre-esser** [bigclick/gambio-gx-multislider#19]
Hi Daniel,

der Slider läuft leider nicht unter der neuen Gambio 2.5.x.x Beta2. Die haben das ganze Admin Interface geändert. ein Upgrade der Version kann ich DIr zukommen lassen.

LG

**Comment by bigclick** [comment]
Hallo André,

Vielen Dank für die Info.

Ja das wäre super. Würde Dir dann wieder die erste Version zum testen zukommen lassen.

LG, Daniel

**Comment by dsiekiera** [comment]
Slider ist aktualisert. Thread wird geschlossen.
