### ISSUE TITLE
Falsche Dateinamen

### ISSUE THREAD

**Issue by netserviceAT** [bigclick/gambio-gx-multislider#22]
in class.slider.php wird eine Templatedatei mit der Endung .html versucht zu laden - im tpl Ordner ist aber die Datei startpage.tpl (kurzfristige "Lösung" daher startpage.tpl in startpage.html umbenennen)

in der admin/multislider.php wird versucht /multislider/js/backend-org.js zu laden - in diesem Ordner ist jedoch nur die Datei backend.js (kurzfristige "Lösung" daher backend.js in backend-org.js umbenennen)

**Comment by dsiekiera** [comment]
Danke für den Hinweis. Da war wohl beim packen was schiefgelaufen.
Wir haben das korririert und aktualisiert.

**Comment by netserviceAT** [comment]
Danke für die rasche Korrektur!
  
 Mit freundlichen Grüßen
  
 Wolfgang Resnicek
 n e t s e r v i c e  [*]
  
  
  

----------------------------------------
 Von: "Daniel Siekiera" <notifications@github.com>
Gesendet: Dienstag, 13. Oktober 2015 15:14
An: "bigclick/gambio-gx-multislider" <gambio-gx-multislider@noreply.github.com>
CC: "netserviceAT" <office@netservice.at>
Betreff: Re: [gambio-gx-multislider] Falsche Dateinamen (#22)   

Danke für den Hinweis. Da war wohl beim packen was schiefgelaufen.
Wir haben das korririert und aktualisiert.  

-

**Comment by netserviceAT** [comment]
Hallo,
  
 nachdem wir heute schon E-Mailkontakt hatten, erlaube ich mir noch eine Frage zu stellen:
  
 Wenn Sie http://demoGAMBIOshop.website-box.at öffnen, sehen Sie Ihren MultiSlider an der Position wie von Ihnen lt. Installationsdoku angegeben (main_content.html).
  
 Wir würden aber den Slider gerne gleich unterhalb der Breadcrumb Navigation in voller Seitenbreite anzeigen (Boxen und Artikel darunter) - kann so etwas funktionieren?
  
 Mit freundlichen Grüßen
  
 Wolfgang Resnicek
 n e t s e r v i c e  [*]
