### ISSUE TITLE
Hallo Liebes Team

### ISSUE THREAD

**Issue by Steffen1** [bigclick/gambio-gx-multislider#6]
Hallo Liebes Team,

ich habe den Multislider installiert und dierkt beim Bild uploaden kommt Synt-ERR. Die Rechte sind 777 und auch die Zielordner angelegt. Kann es daran liegen, dass der Shop nicht im Rootverzeichnis installiert ist und somit unter www.xxxx.de/shop installiert ist? Über Hilfe wäre ich dankbar....

P:S. Habe eben einmal geschaut und das hochgeladene Bild befindet sich in den entsprechenden Ordnern, wurden also hochgeladen.......komisch. Das funktinoniert also schon einmal.....

Bitte um Hilfe und Ideen...

Grüsse
Steffen1

**Comment by bigclick** [comment]
Hallo Steffen1. Ich habe deine Frage gar nicht gefunden. Dieses Problem bestand seiner Zeit noch. Mittlerweile wurde der Slider geupdated und alles läuft wie am Schnürchen. 
Also bitte einfach noch mal Runterladen und wie ein Update anwenden.
