### ISSUE TITLE
Multislider funktioniert nicht

### ISSUE THREAD

**Issue by gemashop** [bigclick/gambio-gx-multislider#8]
Der Multislider zeigt die Bilder nur wie in einer Aufzählung (Liste). Die Bilder bewegen sich auch nicht bzw. kein Fade zu sehen oder ähnliches. Mir kommt es so vor als ob ajax oder java nicht richtig funktioniert, kann jemand helfen?

**Comment by bigclick** [comment]
Es hört sich so an als ob die CSS Datei nicht geladen wurde. Hast Du alle Cache-Dateien gemäß der Anleitung gelöscht?

**Comment by gemashop** [comment]
Jetzt nach Update funktioniert es sehr gut, CSS wird auch geladen. Allerdings stört es uns das die Bilder wie eine Art Schleier drüber haben, Sie sehen nicht mehr richtig scharf aus sondern sind etwas verwaschen. Der Schatten stört uns auch der dahinter liegt, wie kann man diese Sachen abstellen? Dann wäre es eine richtige Alternative zum Standard Gambio-Slider. Desweiteren sollte es eine Möglichkeit geben einen Alt-Tag zu jedem Bild hinterlegen zu können.

Mit freundlichem Gruß
C. Berlig
GEMA GmbH
Anhaltinerring 17
39439 Güsten
Tel. 039262-8787-21
Fax 039262-8787-27
E-Mail c.berlig@gema-net.de
Internet www.gemashop.de 

Sitz der Gesellschaft: Güsten, HRB 14693, Stendal
Gesellschaft mit beschränkter Haftung: GEMA GmbH 
Geschäftsführer: Gerhard Malkowski, Ust-IdNr.: DE187131614, Steuer-Nr.: 116/107/02084

**Comment by bigclick** [comment]
Der Schatten kann über die CSS-Datei komplett abgestellt werden. Das mit dem ALT-Tag schauen wir uns noch einmal an.

**Comment by gemashop** [comment]
Super danke für die Info. Was ist mit den Vor- und Zurück Pfeilen die lassen sich auch nicht komplett entfernen. Wenn man den Slider cleanen möchte, sollte man das können. Momentan geht maximal Pfeile “aus” aber per MouseOver kommen Sie wieder.

Mit freundlichem Gruß
C. Berlig
GEMA GmbH
Anhaltinerring 17
39439 Güsten
Tel. 039262-8787-21
Fax 039262-8787-27
E-Mail c.berlig@gema-net.de
Internet www.gemashop.de 

Sitz der Gesellschaft: Güsten, HRB 14693, Stendal
Gesellschaft mit beschränkter Haftung: GEMA GmbH 
Geschäftsführer: Gerhard Malkowski, Ust-IdNr.: DE187131614, Steuer-Nr.: 116/107/02084

**Comment by gemashop** [comment]
Kann du uns bitte noch verraten unter welcher CSS-class wird den Schatten entfernen können? Wir würden auch gerne das die Bilder schärfer angezeigt werden, momentan ist irgendetwas drübergezogen was die Grafik blass und unscharf erscheinen lässt, deshalb haben wir momentan wieder auf unseren Standard Slider geschalten. Könnt ihr uns sagen an welcher Stelle das in der CSS verankert ist?

Mit freundlichem Gruß
C. Berlig
GEMA GmbH
Anhaltinerring 17
39439 Güsten
Tel. 039262-8787-21
Fax 039262-8787-27
E-Mail c.berlig@gema-net.de
Internet www.gemashop.de 

Sitz der Gesellschaft: Güsten, HRB 14693, Stendal
Gesellschaft mit beschränkter Haftung: GEMA GmbH 
Geschäftsführer: Gerhard Malkowski, Ust-IdNr.: DE187131614, Steuer-Nr.: 116/107/02084

**Comment by dsiekiera** [comment]
Alles schick...
