### ISSUE TITLE
Style-edit funktioniert nicht

### ISSUE THREAD

**Issue by paunho** [bigclick/gambio-gx-multislider#9]
Ich habe den gambio gx multislider entsprechend ihren angaben installiert und jetzt geht der style edit nicht mehr können Sie mir bitte helfen ist nämlich ein sehr schöner slider.
MFG
benutze version gambio gx2 2.1,5,2

**Comment by bigclick** [comment]
Hallo, haben sie alle Cache-Ordner gelöscht?

**Comment by paunho** [comment]
hab ich

**Comment by paunho** [comment]
Hat sich erledigt 
Danke noch mal 
Mfg paunho
